(test
 (name test_codec)
 (modules test_codec)
 (libraries jose))

(test
 (name test_hmac)
 (modules test_hmac)
 (libraries jose))

(test
 (name test_jwt)
 (modules test_jwt)
 (libraries jose))

(test
 (name test_limbs)
 (modules test_limbs)
 (libraries jose))

(test
 (name test_rsa)
 (modules test_rsa)
 (libraries jose))

(test
 (name test_p256)
 (modules test_p256)
 (libraries jose))

(test
 (name test_jwk)
 (modules test_jwk)
 (libraries jose))
